[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "dark"
primaryColor = "#00c9ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e2130"
textColor = "#ffffff"
font = "sans serif"
